// Данные автомобилей для автопарка
const carData = {
    // Седаны
    hyundai_bayon_71586: {
        id: 'hyundai_bayon_71586',
        title: 'Hyundai Bayon',
        description: 'Компактный и экономичный городской кроссовер.',
        type: 'crossover',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Кроссовер',
        year: '2024',
        priceMain: '25 000 ₸/сутки',
        basePrice: 25000,
        priceDiscount: '22 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 25000 },
            { minDays: 3, maxDays: 5, price: 22000 },
            { minDays: 6, maxDays: 15, price: 19000 },
            { minDays: 16, maxDays: 31, price: 16000 },
            { minDays: 31, price: 13000 }
        ],
        features: ['Кондиционер', 'Мультимедийная система', 'Электростеклоподъемники'],
        images: ['hyundai-bayon-1.JPG', 'hyundai-bayon-2.JPG', 'hyundai-bayon-3.JPG', 'hyundai-bayon-4.JPG', 'hyundai-bayon-5.JPG'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '533 ARF 01',
        deposit: '20 000 ₸',
        pricePerHour: '2 000 ₸/час',
        city: 'astana'
    },

    geely_mgrand_72104: {
        id: 'geely_mgrand_72104',
        title: 'Geely MGrand',
        description: 'Современный седан с хорошей комплектацией и экономичным двигателем.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2024',
        priceMain: '30 000 ₸/сутки',
        basePrice: 30000,
        priceDiscount: '27 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 30000 },
            { minDays: 3, maxDays: 5, price: 27000 },
            { minDays: 6, maxDays: 15, price: 25500 },
            { minDays: 16, maxDays: 31, price: 24000 },
            { minDays: 31, price: 22500 }
        ],
        features: ['Климат-контроль', 'Мультимедийная система', 'Камера заднего вида'],
        images: ['geely-1.jpeg', 'geely-2.jpeg', 'geely-3.jpeg', 'geely-4.jpeg', 'geely-5.jpeg', 'geely-6.jpeg', 'geely-7.jpeg'],
        color: 'linear-gradient(135deg, #808080, #a9a9a9)',
        carNumber: '111 ABA 01',
        deposit: '20 000 ₸',
        pricePerHour: '2 000 ₸/час',
        city: 'astana'
    },

    zeekr_001_72415: {
        id: 'zeekr_001_72415',
        title: 'ZEEKR 001',
        description: 'Электрический премиум автомобиль с передовыми технологиями.',
        type: 'premium',
        priceSegment: 'premium',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Электрический',
        carType: 'Хэтчбек',
        year: '2023',
        priceMain: '60 000 ₸/сутки',
        basePrice: 60000,
        priceDiscount: '54 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 60000 },
            { minDays: 3, maxDays: 5, price: 54000 },
            { minDays: 6, maxDays: 15, price: 48000 },
            { minDays: 16, maxDays: 31, price: 42000 },
            { minDays: 31, price: 35000 }
        ],
        features: ['Электропривод', 'Панорамная крыша', 'Премиум аудио', 'Автопилот'],
        images: ['zeekr-001-1.jpg', 'zeekr-001-2.jpg', 'zeekr-001-3.jpg', 'zeekr-001-4.jpg', 'zeekr-001-5.jpg'],
        color: 'linear-gradient(135deg, #87CEEB, #4682B4)',
        carNumber: '323 AQZ 01',
        deposit: '30 000 ₸',
        pricePerHour: '3 000 ₸/час',
        city: 'astana'
    },

    toyota_camry_75_4wd_73291: {
        id: 'toyota_camry_75_4wd_73291',
        title: 'Toyota Camry 75 4WD',
        description: 'Надежный полноприводный седан с отличной проходимостью и комфортом.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2021',
        priceMain: '40 000 ₸/сутки',
        basePrice: 40000,
        priceDiscount: '36 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 40000 },
            { minDays: 3, maxDays: 5, price: 36000 },
            { minDays: 6, maxDays: 15, price: 32000 },
            { minDays: 16, maxDays: 31, price: 28000 },
            { minDays: 31, price: 25000 }
        ],
        features: ['Полный привод', 'Климат-контроль', 'Камера заднего вида', 'Круиз-контроль'],
        images: ['camry-75-1.jpeg', 'camry-75-2.jpeg', 'camry-75-3.jpeg', 'camry-75-4.jpeg', 'camry-75-5.jpeg', 'camry-75-6.jpeg', 'camry-75-7.jpeg'],
        color: 'linear-gradient(135deg, #ffffff, #e0e0e0)',
        carNumber: '087 AXC 09',
        deposit: '30 000 ₸',
        pricePerHour: '2 500 ₸/час',
        city: 'astana'
    },

    hyundai_grandeur_73624: {
        id: 'hyundai_grandeur_73624',
        title: 'Hyundai Grandeur',
        description: 'Представительский седан премиум-класса с роскошным интерьером.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        priceMain: '40 000 ₸/сутки',
        basePrice: 40000,
        priceDiscount: '36 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 40000 },
            { minDays: 3, maxDays: 5, price: 36000 },
            { minDays: 6, maxDays: 15, price: 32000 },
            { minDays: 16, maxDays: 31, price: 28000 },
            { minDays: 31, price: 25000 }
        ],
        features: ['Климат-контроль', 'Кожаный салон', 'Камера заднего вида', 'Подогрев сидений'],
        images: ['grandeur-1.jpeg', 'grandeur-2.jpeg', 'grandeur-3.jpeg', 'grandeur-4.jpeg', 'grandeur-5.jpeg', 'grandeur-6.jpeg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '694 ATO 17',
        deposit: '30 000 ₸',
        pricePerHour: '2 500 ₸/час',
        city: 'astana'
    },

    toyota_camry_73623: {
        id: 'toyota_camry_73623',
        title: 'Toyota Camry',
        description: 'Комфортный седан в стильном сером цвете для деловых и личных поездок.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2023',
        priceMain: '40 000 ₸/сутки',
        basePrice: 40000,
        priceDiscount: '36 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 40000 },
            { minDays: 3, maxDays: 5, price: 36000 },
            { minDays: 6, maxDays: 15, price: 32000 },
            { minDays: 16, maxDays: 31, price: 28000 },
            { minDays: 31, price: 25000 }
        ],
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Мультимедийная система'],
        images: [],
        color: 'linear-gradient(135deg, #808080, #a9a9a9)',
        carNumber: '101 NSE 01',
        deposit: '30 000 ₸',
        pricePerHour: '2 500 ₸/час',
        city: 'astana'
    },

    hyundai_santa_fe_73622: {
        id: 'hyundai_santa_fe_73622',
        title: 'Hyundai Santa Fe',
        description: 'Новейший кроссовер с современным дизайном и богатой комплектацией.',
        type: 'crossover',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Кроссовер',
        year: '2025',
        priceMain: '60 000 ₸/сутки',
        basePrice: 60000,
        priceDiscount: '54 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 60000 },
            { minDays: 3, maxDays: 5, price: 54000 },
            { minDays: 6, maxDays: 15, price: 48000 },
            { minDays: 16, maxDays: 31, price: 42000 },
            { minDays: 31, price: 35000 }
        ],
        features: ['Полный привод', 'Трехзонный климат-контроль', 'Панорамная крыша', 'Камера 360°'],
        images: ['santa-fe-1.jpeg', 'santa-fe-2.jpeg', 'santa-fe-3.jpeg', 'santa-fe-4.jpeg', 'santa-fe-5.jpeg', 'santa-fe-6.jpeg', 'santa-fe-7.jpeg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '471 BBO 01',
        deposit: '30 000 ₸',
        pricePerHour: '3 000 ₸/час',
        city: 'astana'
    },

    jetour_x90_plus_73625: {
        id: 'jetour_x90_plus_73625',
        title: 'Jetour X90 Plus',
        description: 'Просторный и современный кроссовер для комфортных семейных поездок.',
        type: 'crossover',
        priceSegment: 'comfort',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Кроссовер',
        year: '2024',
        priceMain: '30 000 ₸/сутки',
        basePrice: 30000,
        priceDiscount: '27 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 30000 },
            { minDays: 3, maxDays: 5, price: 27000 },
            { minDays: 6, maxDays: 15, price: 24000 },
            { minDays: 16, maxDays: 31, price: 21000 },
            { minDays: 31, price: 20000 }
        ],
        features: ['Панорамная крыша', 'Мультимедийная система', 'Камера заднего вида', 'Климат-контроль'],
        images: ['jetour-x90-1.jpeg', 'jetour-x90-2.jpeg', 'jetour-x90-3.jpeg', 'jetour-x90-4.jpeg', 'jetour-x90-5.jpeg'],
        color: 'linear-gradient(135deg, #808080, #a9a9a9)',
        carNumber: '868 BGO 02',
        deposit: '—',
        pricePerHour: '—',
        city: 'astana'
    },

    hyundai_sonata_40892: {
        id: 'hyundai_sonata_40892',
        title: 'Hyundai Sonata',
        description: 'Стильный и комфортный седан для городских поездок и путешествий.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2023',
        priceMain: '40 000 ₸/сутки',
        basePrice: 40000,
        priceDiscount: '36 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 40000 },
            { minDays: 3, maxDays: 5, price: 36000 },
            { minDays: 6, maxDays: 15, price: 32000 },
            { minDays: 16, maxDays: 31, price: 28000 },
            { minDays: 31, price: 26000 }
        ],
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Мультимедийная система'],
        images: ['hyundai-sonata (1).jpg', 'hyundai-sonata (2).jpg', 'hyundai-sonata (3).jpg', 'hyundai-sonata (4).jpg', 'hyundai-sonata (5).jpg', 'hyundai-sonata (6).jpg', 'hyundai-sonata (7).jpg', 'hyundai-sonata (8).jpg'],
        color: 'linear-gradient(135deg, #ffffff, #e0e0e0)',
        carNumber: '565 ANI 01',
        deposit: '20 000 ₸',
        pricePerHour: '2 500 ₸/час',
        city: 'astana'
    },

    hyundai_santa_fe_40891: {
        id: 'hyundai_santa_fe_40891',
        title: 'Hyundai Santa Fe',
        description: 'Просторный кроссовер для семьи и путешествий по любым дорогам.',
        type: 'crossover',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Кроссовер',
        year: '2022',
        priceMain: '45 000 ₸/сутки',
        basePrice: 45000,
        priceDiscount: '40 500 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 45000 },
            { minDays: 3, maxDays: 5, price: 40500 },
            { minDays: 6, maxDays: 15, price: 36000 },
            { minDays: 16, maxDays: 31, price: 31500 },
            { minDays: 31, price: 27000 }
        ],
        features: ['Полный привод', 'Трехзонный климат-контроль', 'Панорамная крыша', 'Система парковки'],
        images: ['santa-fe (1).jpg', 'santa-fe (2).jpg', 'santa-fe (3).jpg', 'santa-fe (4).jpg', 'santa-fe (5).jpg', 'santa-fe (6).jpg', 'santa-fe (7).jpg', 'santa-fe (8).jpg', 'santa-fe (9).jpg'],
        color: 'linear-gradient(135deg, #8B4513, #000080)',
        carNumber: '905 ZCP 01',
        deposit: '20 000 ₸',
        pricePerHour: '2 500 ₸/час',
        city: 'astana'
    },

    toyota_camry_65265: {
        id: 'toyota_camry_65265',
        title: 'Toyota Camry',
        description: 'Надежный и комфортный седан для городских поездок и путешествий.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2025',
        priceMain: '60 000 ₸/сутки',
        basePrice: 60000,
        priceDiscount: '54 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 60000 },
            { minDays: 3, maxDays: 5, price: 54000 },
            { minDays: 6, maxDays: 15, price: 48000 },
            { minDays: 16, maxDays: 31, price: 42000 },
            { minDays: 31, price: 39000 }
        ],
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Подогрев сидений'],
        images: ['toyota-camry-1.PNG', 'toyota-camry-2.PNG', 'toyota-camry-3.PNG', 'toyota-camry-4.PNG', 'toyota-camry-5.PNG', 'toyota-camry-6.PNG', 'toyota-camry-7.PNG', 'toyota-camry-8.PNG'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '099 AWY 01',
        deposit: '20 000 ₸',
        pricePerHour: '3 000 ₸/час',
        city: 'astana'
    },

    hyundai_palisade_50339: {
        id: 'hyundai_palisade_50339',
        title: 'Hyundai Palisade',
        description: 'Просторный полноразмерный внедорожник премиум-класса.',
        type: 'suv',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Внедорожник',
        year: '2024',
        priceMain: '70 000 ₸/сутки',
        basePrice: 70000,
        priceDiscount: '63 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 70000 },
            { minDays: 3, maxDays: 5, price: 63000 },
            { minDays: 6, maxDays: 15, price: 56000 },
            { minDays: 16, maxDays: 31, price: 49000 },
            { minDays: 31, price: 42000 }
        ],
        features: ['Полный привод', 'Память сидений', 'Вентиляция сидений', 'Хэд-ап дисплей'],
        images: ['palisade (1).jpg', 'palisade (2).jpg', 'palisade (3).jpg', 'palisade (4).jpg', 'palisade (5).jpg', 'palisade (6).jpg', 'palisade (7).jpg', 'palisade (8).jpg', 'palisade (9).jpg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '545 CAZ 01',
        deposit: '20 000 ₸',
        pricePerHour: '3 300 ₸/час',
        city: 'astana'
    },

    chery_tiggo_7_pro_64982: {
        id: 'chery_tiggo_7_pro_64982',
        title: 'Cherry Tiggo 7 Pro',
        description: 'Современный кроссовер с богатой комплектацией и стильным дизайном.',
        type: 'crossover',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Кроссовер',
        year: '2023',
        priceMain: '30 000 ₸/сутки',
        basePrice: 30000,
        priceDiscount: '27 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 30000 },
            { minDays: 3, maxDays: 5, price: 27000 },
            { minDays: 6, maxDays: 15, price: 24000 },
            { minDays: 16, maxDays: 31, price: 21000 },
            { minDays: 31, price: 20000 }
        ],
        features: ['Панорамная крыша', 'Камера 360°', 'Бесключевой доступ', 'Светодиодные фары'],
        images: ['cherry-tiggo (1).jpg', 'cherry-tiggo (2).jpg', 'cherry-tiggo (3).jpg', 'cherry-tiggo (4).jpg', 'cherry-tiggo (5).jpg', 'cherry-tiggo (6).jpg'],
        color: 'linear-gradient(135deg, #ffffff, #e0e0e0)',
        carNumber: '926 ALB 01',
        deposit: '20 000 ₸',
        pricePerHour: '1 500 ₸/час',
        city: 'astana'
    },

    toyota_camry_71088: {
        id: 'toyota_camry_71088',
        title: 'Toyota Camry',
        description: 'Обновленная версия популярного седана с улучшенной комфортностью.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2024',
        priceMain: '50 000 ₸/сутки',
        basePrice: 50000,
        priceDiscount: '45 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 50000 },
            { minDays: 3, maxDays: 5, price: 45000 },
            { minDays: 6, maxDays: 15, price: 40000 },
            { minDays: 16, maxDays: 31, price: 35000 },
            { minDays: 31, price: 30000 }
        ],
        features: ['Обновленный дизайн', 'Улучшенная шумоизоляция', 'Мультимедийная система'],
        images: ['toyota-camry-1.PNG', 'toyota-camry-2.PNG', 'toyota-camry-3.PNG', 'toyota-camry-4.PNG', 'toyota-camry-5.PNG', 'toyota-camry-6.PNG', 'toyota-camry-7.PNG', 'toyota-camry-8.PNG'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '373 ALT 01',
        deposit: '20 000 ₸',
        pricePerHour: '3 000 ₸/час',
        city: 'astana'
    },

    hyundai_custin_65678: {
        id: 'hyundai_custin_65678',
        title: 'Hyundai Custin',
        description: 'Вместительный минивэн для комфортных поездок большой компанией.',
        type: 'minivan',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Минивэн',
        year: '2024',
        priceMain: '45 000 ₸/сутки',
        basePrice: 45000,
        priceDiscount: '40 500 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 45000 },
            { minDays: 3, maxDays: 5, price: 40500 },
            { minDays: 6, maxDays: 15, price: 36000 },
            { minDays: 16, maxDays: 31, price: 31500 },
            { minDays: 31, price: 27000 }
        ],
        features: ['Сдвижные двери', 'Трехзонный климат-контроль', 'Система парковки', 'Подогрев сидений'],
        images: ['hyundai-custin (2).jpg', 'hyundai-custin (3).jpg', 'hyundai-custin (4).jpg', 'hyundai-custin (5).jpg', 'hyundai-custin (6).jpg', 'hyundai-custin (7).jpg'],
        color: 'linear-gradient(135deg, #8B4513, #A0522D)',
        carNumber: '025 AXH 01',
        deposit: '20 000 ₸',
        pricePerHour: '3 000 ₸/час',
        city: 'astana'
    },

    jetour_t2_66170: {
        id: 'jetour_t2_66170',
        title: 'Jetour T2',
        description: 'Стильный кроссовер для активного образа жизни и путешествий.',
        type: 'crossover',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Кроссовер',
        year: '2025',
        priceMain: '45 000 ₸/сутки',
        basePrice: 45000,
        priceDiscount: '40 500 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 45000 },
            { minDays: 3, maxDays: 5, price: 40500 },
            { minDays: 6, maxDays: 15, price: 36000 },
            { minDays: 16, maxDays: 31, price: 31500 },
            { minDays: 31, price: 27000 }
        ],
        features: ['Полный привод', 'Мультимедийная система', 'Подогрев сидений', 'Круиз-контроль'],
        images: ['jetour-t2 (1).jpg', 'jetour-t2 (2).jpg', 'jetour-t2 (3).jpg', 'jetour-t2 (4).jpg', 'jetour-t2 (5).jpg'],
        color: 'linear-gradient(135deg, #ffffff, #e0e0e0)',
        carNumber: '958 AWR 01',
        deposit: '30 000 ₸',
        pricePerHour: '2 500 ₸/час',
        city: 'astana'
    },

    kia_carnival_67829: {
        id: 'kia_carnival_67829',
        title: 'KIA Carnival',
        description: 'Просторный и комфортабельный минивэн премиум-класса.',
        type: 'minivan',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Минивэн',
        year: '2023',
        priceMain: '70 000 ₸/сутки',
        basePrice: 70000,
        priceDiscount: '63 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 70000 },
            { minDays: 3, maxDays: 5, price: 63000 },
            { minDays: 6, maxDays: 15, price: 56000 },
            { minDays: 16, maxDays: 31, price: 49000 },
            { minDays: 31, price: 42000 }
        ],
        features: ['Электропривод дверей', 'Двухзонный климат-контроль', 'Система развлечений', 'Подогрев руля'],
        images: ['kia-carnival (2).jpg', 'kia-carnival (3).jpg', 'kia-carnival (4).jpg', 'kia-carnival (5).jpg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '971 ASY 01',
        deposit: '30 000 ₸',
        pricePerHour: '3 500 ₸/час',
        city: 'astana'
    },

    lixiang_l9_ultra_59408: {
        id: 'lixiang_l9_ultra_59408',
        title: 'Lixiang L9 Ultra',
        description: 'Инновационный гибридный внедорожник премиум-класса с передовыми технологиями.',
        type: 'premium',
        priceSegment: 'premium',
        seats: '6 мест',
        transmission: 'Автомат',
        fuel: 'Гибрид',
        carType: 'Внедорожник',
        year: '2024',
        priceMain: '120 000 ₸/сутки',
        basePrice: 120000,
        priceDiscount: '108 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 120000 },
            { minDays: 3, maxDays: 5, price: 108000 },
            { minDays: 6, maxDays: 15, price: 96000 },
            { minDays: 16, maxDays: 31, price: 84000 },
            { minDays: 31, price: 72000 }
        ],
        features: ['Гибридная установка', 'Автопилот', 'Премиум аудио', 'Массаж сидений', 'Панорамная крыша'],
        images: ['lixiang (1).jpg', 'lixiang (2).jpg', 'lixiang (3).jpg', 'lixiang (4).jpg', 'lixiang (5).jpg', 'lixiang (6).jpg', 'lixiang (7).jpg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '999 KOS 01',
        deposit: '30 000 ₸',
        pricePerHour: '6 000 ₸/час',
        city: 'astana'
    },

    toyota_camry_75_50336: {
        id: 'toyota_camry_75_50336',
        title: 'Toyota Camry 75',
        description: 'Надежный и стильный седан в чёрном цвете для деловых поездок.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2023',
        priceMain: '40 000 ₸/сутки',
        basePrice: 40000,
        priceDiscount: '36 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 40000 },
            { minDays: 3, maxDays: 5, price: 36000 },
            { minDays: 6, maxDays: 15, price: 32000 },
            { minDays: 16, maxDays: 31, price: 28000 },
            { minDays: 31, price: 26000 }
        ],
        features: ['Климат-контроль', 'Круиз-контроль', 'Мультимедийная система', 'Подогрев сидений'],
        images: ['toyota-camry-75-1.JPG', 'toyota-camry-75-2.JPG', 'toyota-camry-75-3.JPG', 'toyota-camry-75-4.JPG', 'toyota-camry-75-5.JPG', 'toyota-camry-75-6.JPG', 'toyota-camry-75-7.JPG', 'toyota-camry-75-8.JPG', 'toyota-camry-75-9.JPG'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '101 GPA 01',
        deposit: '30 000 ₸',
        pricePerHour: '2 500 ₸/час',
        city: 'astana'
    },

    toyota_camry_66223: {
        id: 'toyota_camry_66223',
        title: 'Toyota Camry 75',
        description: 'Классический седан с отличной репутацией надежности.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2021',
        priceMain: '40 000 ₸/сутки',
        basePrice: 40000,
        priceDiscount: '36 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 40000 },
            { minDays: 3, maxDays: 5, price: 36000 },
            { minDays: 6, maxDays: 15, price: 32000 },
            { minDays: 16, maxDays: 31, price: 28000 },
            { minDays: 31, price: 25000 }
        ],
        features: ['Кондиционер', 'Круиз-контроль', 'Мультимедийная система'],
        images: ['toyota-camry-070-1.JPG', 'toyota-camry-070-2.JPG', 'toyota-camry-070-3.JPG', 'toyota-camry-070-4.JPG', 'toyota-camry-070-5.JPG', 'toyota-camry-070-6.JPG', 'toyota-camry-070-7.JPG', 'toyota-camry-070-8.JPG', 'toyota-camry-070-9.JPG', 'toyota-camry-070-10.JPG'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '070 ZEE 17',
        deposit: '30 000 ₸',
        pricePerHour: '2 500 ₸/час',
        city: 'astana'
    },

    toyota_camry_70_55028: {
        id: 'toyota_camry_70_55028',
        title: 'Toyota Camry 70',
        description: 'Надежный седан для деловых поездок и повседневного использования.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2018',
        priceMain: '35 000 ₸/сутки',
        basePrice: 35000,
        priceDiscount: '31 500 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 35000 },
            { minDays: 3, maxDays: 5, price: 31500 },
            { minDays: 6, maxDays: 15, price: 28000 },
            { minDays: 16, maxDays: 31, price: 24500 },
            { minDays: 31, price: 21000 }
        ],
        features: ['Кондиционер', 'Электростеклоподъемники', 'Мультимедийная система'],
        images: [],
        color: 'linear-gradient(135deg, #ffffff, #e0e0e0)',
        carNumber: '051 AQI 01',
        deposit: '20 000 ₸',
        pricePerHour: '2 000 ₸/час',
        city: 'astana'
    },

    toyota_camry_70_40896: {
        id: 'toyota_camry_70_40896',
        title: 'Toyota Camry 70',
        description: 'Проверенный временем седан с оптимальным сочетанием цены и качества.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2020',
        priceMain: '30 000 ₸/сутки',
        basePrice: 30000,
        priceDiscount: '27 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 30000 },
            { minDays: 3, maxDays: 5, price: 27000 },
            { minDays: 6, maxDays: 15, price: 24000 },
            { minDays: 16, maxDays: 31, price: 21000 },
            { minDays: 31, price: 20000 }
        ],
        features: ['Кондиционер', 'Круиз-контроль', 'Мультимедийная система'],
        images: ['toyota_cmary (1).jpg', 'toyota_cmary (2).jpg', 'toyota_cmary (3).jpg', 'toyota_cmary (4).jpg', 'toyota_cmary (5).jpg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '021 ALJ 01',
        deposit: '20 000 ₸',
        pricePerHour: '2 000 ₸/час',
        city: 'astana'
    },

    hyundai_sonata_40893: {
        id: 'hyundai_sonata_40893',
        title: 'Hyundai Sonata',
        description: 'Современный седан с хорошей экономичностью и комфортом.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        priceMain: '35 000 ₸/сутки',
        basePrice: 35000,
        priceDiscount: '31 500 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 35000 },
            { minDays: 3, maxDays: 5, price: 31500 },
            { minDays: 6, maxDays: 15, price: 28000 },
            { minDays: 16, maxDays: 31, price: 24500 },
            { minDays: 31, price: 21000 }
        ],
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Мультимедийная система'],
        images: ['hyundai-sonta (1).jpg', 'hyundai-sonta (2).jpg', 'hyundai-sonta (3).jpg', 'hyundai-sonta (4).jpg', 'hyundai-sonta (5).jpg', 'hyundai-sonta (6).jpg', 'hyundai-sonta (7).jpg', 'hyundai-sonta (8).jpg'],
        color: 'linear-gradient(135deg, #808080, #a9a9a9)',
        carNumber: '769 AMJ 01',
        deposit: '20 000 ₸',
        pricePerHour: '2 000 ₸/час',
        city: 'astana'
    },

    hyundai_sonata_66808: {
        id: 'hyundai_sonata_66808',
        title: 'Hyundai Sonata',
        description: 'Современный седан с привлекательным дизайном и хорошей комплектацией.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2025',
        priceMain: '40 000 ₸/сутки',
        basePrice: 40000,
        priceDiscount: '36 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 40000 },
            { minDays: 3, maxDays: 5, price: 36000 },
            { minDays: 6, maxDays: 15, price: 32000 },
            { minDays: 16, maxDays: 31, price: 28000 },
            { minDays: 31, price: 25000 }
        ],
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Светодиодные фары'],
        images: ['hyundai-sona (1).jpg', 'hyundai-sona (2).jpg', 'hyundai-sona (3).jpg', 'hyundai-sona (4).jpg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '088 AXK 01',
        deposit: '20 000 ₸',
        pricePerHour: '2 000 ₸/час',
        city: 'astana'
    },

    hyundai_elantra_54419: {
        id: 'hyundai_elantra_54419',
        title: 'Hyundai Elantra',
        description: 'Экономичный и практичный седан для повседневных поездок.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        priceMain: '25 000 ₸/сутки',
        basePrice: 25000,
        priceDiscount: '22 500 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 25000 },
            { minDays: 3, maxDays: 5, price: 22500 },
            { minDays: 6, maxDays: 15, price: 20000 },
            { minDays: 16, maxDays: 31, price: 17500 },
            { minDays: 31, price: 15000 }
        ],
        features: ['Кондиционер', 'Мультимедийная система', 'Электроусилитель руля'],
        images: ['hyundai-elantra (1).jpg', 'hyundai-elantra (2).jpg', 'hyundai-elantra (3).jpg', 'hyundai-elantra (4).jpg', 'hyundai-elantra (5).jpg', 'hyundai-elantra (6).jpg', 'hyundai-elantra (7).jpg'],
        color: 'linear-gradient(135deg, #ffffff, #e0e0e0)',
        carNumber: '134 AFV 01',
        deposit: '20 000 ₸',
        pricePerHour: '1 500 ₸/час',
        city: 'astana'
    },

    bmw_530i_68139: {
        id: 'bmw_530i_68139',
        title: 'BMW 530i',
        description: 'Премиальный седан бизнес-класса с динамичными характеристиками.',
        type: 'sedan',
        priceSegment: 'business',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2017',
        priceMain: '60 000 ₸/сутки',
        basePrice: 60000,
        priceDiscount: '54 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 60000 },
            { minDays: 3, maxDays: 5, price: 54000 },
            { minDays: 6, maxDays: 15, price: 48000 },
            { minDays: 16, maxDays: 31, price: 42000 },
            { minDays: 31, price: 36000 }
        ],
        features: ['Кожаный салон', 'Навигационная система', 'Панорамная крыша', 'Подогрев сидений'],
        images: ['bmw (1).jpg', 'bmw (2).jpg', 'bmw (3).jpg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '414 ASV 01',
        deposit: '30 000 ₸',
        pricePerHour: '3 500 ₸/час',
        city: 'astana'
    },

    infiniti_qx80_51163: {
        id: 'infiniti_qx80_51163',
        title: 'Infiniti QX80',
        description: 'Полноразмерный роскошный внедорожник премиум-класса.',
        type: 'suv',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Внедорожник',
        year: '2021',
        priceMain: '80 000 ₸/сутки',
        basePrice: 80000,
        priceDiscount: '72 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 80000 },
            { minDays: 3, maxDays: 5, price: 72000 },
            { minDays: 6, maxDays: 15, price: 66000 },
            { minDays: 16, maxDays: 31, price: 58000 },
            { minDays: 31, price: 45000 }
        ],
        features: ['Полный привод', 'Премиум кожа', 'Телематика', 'Камера 360°'],
        images: ['infinity (1).jpg', 'infinity (2).jpg', 'infinity (3).jpg', 'infinity (4).jpg', 'infinity (5).jpg', 'infinity (6).jpg', 'infinity (7).jpg', 'infinity (8).jpg', 'infinity (9).jpg'],
        color: 'linear-gradient(135deg, #808080, #a9a9a9)',
        carNumber: '552 BBK 01',
        deposit: '40 000 ₸',
        pricePerHour: '4 500 ₸/час',
        city: 'astana'
    },

    hyundai_sonata_61325: {
        id: 'hyundai_sonata_61325',
        title: 'Hyundai Sonata',
        description: 'Современный седан с привлекательным дизайном и хорошей комплектацией.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2025',
        priceMain: '40 000 ₸/сутки',
        basePrice: 40000,
        priceDiscount: '36 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 40000 },
            { minDays: 3, maxDays: 5, price: 36000 },
            { minDays: 6, maxDays: 15, price: 32000 },
            { minDays: 16, maxDays: 31, price: 28000 },
            { minDays: 31, price: 25000 }
        ],
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Светодиодные фары'],
        images: ['hyunda-sonata (1).jpg', 'hyunda-sonata (2).jpg', 'hyunda-sonata (3).jpg', 'hyunda-sonata (4).jpg', 'hyunda-sonata (5).jpg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '024 AUQ 01',
        deposit: '30 000 ₸',
        pricePerHour: '2 000 ₸/час',
        city: 'astana'
    },

    lexus_570_60001: {
        id: 'lexus_570_60001',
        title: 'Lexus 570',
        description: 'Легендарный роскошный внедорожник с мощным двигателем и премиум комфортом.',
        type: 'suv',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Внедорожник',
        year: '2016',
        priceMain: '130 000 ₸/сутки',
        basePrice: 130000,
        priceDiscount: '117 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 130000 },
            { minDays: 3, maxDays: 5, price: 117000 },
            { minDays: 6, maxDays: 15, price: 104000 },
            { minDays: 16, maxDays: 31, price: 91000 },
            { minDays: 31, price: 78000 }
        ],
        features: ['Полный привод', 'Пневмоподвеска', 'Массаж сидений', 'Премиум аудио', 'Панорамная крыша'],
        images: ['lexus-570-grey (1).jpg', 'lexus-570-grey (2).jpg', 'lexus-570-grey (3).jpg', 'lexus-570-grey (4).jpg', 'lexus-570-grey (5).jpg', 'lexus-570-grey (6).jpg'],
        color: 'linear-gradient(135deg, #808080, #a9a9a9)',
        carNumber: '580 BGT 02',
        deposit: '40 000 ₸',
        pricePerHour: '6 000 ₸/час',
        city: 'astana'
    },

    lexus_lx_570_52558: {
        id: 'lexus_lx_570_52558',
        title: 'Lexus LX 570',
        description: 'Легендарный роскошный внедорожник с мощным двигателем.',
        type: 'suv',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Внедорожник',
        year: '2014',
        priceMain: '60 000 ₸/сутки',
        basePrice: 60000,
        priceDiscount: '54 000 ₸/сутки при аренде от 3 дней',
        periods: [
            { minDays: 1, maxDays: 2, price: 60000 },
            { minDays: 3, maxDays: 5, price: 54000 },
            { minDays: 6, maxDays: 15, price: 48000 },
            { minDays: 16, maxDays: 31, price: 42000 },
            { minDays: 31, price: 39000 }
        ],
        features: ['Полный привод', 'Пневмоподвеска', 'Массаж сидений', 'Премиум аудио'],
        images: ['lexus-570-black (1).jpg', 'lexus-570-black (2).jpg'],
        color: 'linear-gradient(135deg, #000000, #333333)',
        carNumber: '023 AJB 01',
        deposit: '40 000 ₸',
        pricePerHour: '3 350 ₸/час',
        city: 'astana'
    }
};
