// Данные автомобилей для автопарка
const carData = {
    // Премиум класс
    mercedes: {
        id: 'mercedes',
        title: 'Mercedes-Benz S-Class',
        description: 'Роскошный седан бизнес-класса с максимальным комфортом и передовыми технологиями.',
        type: 'premium',
        priceSegment: 'premium',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2023',
        mileage: '15 000 км',
        priceMain: '25 000 ₸/сутки',
        basePrice: 25000,
        priceDiscount: '22 000 ₸/сутки при аренде от 3 дней',
        features: ['Климат-контроль', 'Кожаный салон', 'Панорамная крыша', 'Подогрев сидений', 'Система навигации'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #6a9ae8, #4a7bc8)',
        city: 'astana'
    },

    // Седаны
    hyundai_sonata_40892: {
        id: 'hyundai_sonata_40892',
        title: 'Hyundai Sonata 2022',
        description: 'Стильный и комфортный седан для городских поездок и путешествий.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        mileage: '25 000 км',
        priceMain: '12 000 ₸/сутки',
        basePrice: 12000,
        priceDiscount: '10 000 ₸/сутки при аренде от 3 дней',
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Мультимедийная система'],
        images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
        color: 'linear-gradient(135deg, #667eea, #764ba2)',
        city: 'astana'
    },
    hyundai_sonata_40893: {
        id: 'hyundai_sonata_40893',
        title: 'Hyundai Sonata 2024',
        description: 'Современный седан с отличной экономичностью и комфортом.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        mileage: '28 000 км',
        priceMain: '12 000 ₸/сутки',
        basePrice: 12000,
        priceDiscount: '10 000 ₸/сутки при аренде от 3 дней',
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Мультимедийная система'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #667eea, #764ba2)',
        city: 'almaty'
    },
    toyota_camry_65265: {
        id: 'toyota_camry_65265',
        title: 'Toyota Camry',
        description: 'Надежный и комфортный седан для городских поездок и путешествий.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        mileage: '20 000 км',
        priceMain: '13 000 ₸/сутки',
        basePrice: 13000,
        priceDiscount: '11 000 ₸/сутки при аренде от 3 дней',
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Подогрев сидений', 'Мультимедийная система'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #ff6b6b, #ff8e8e)',
        city: 'astana'
    },
    kia_k5_69801: {
        id: 'kia_k5_69801',
        title: 'KIA K5',
        description: 'Спортивный седан с современным дизайном и отличной управляемостью.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2023',
        mileage: '15 000 км',
        priceMain: '14 000 ₸/сутки',
        basePrice: 14000,
        priceDiscount: '12 000 ₸/сутки при аренде от 3 дней',
        features: ['Климат-контроль', 'Спортивный режим', 'Камера 360°', 'Премиальная аудиосистема'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #4ecdc4, #44a08d)',
        city: 'almaty'
    },
    omoda_c5_50337: {
        id: 'omoda_c5_50337',
        title: 'OMODA C5',
        description: 'Современный кросс-седан с инновационным дизайном и технологиями.',
        type: 'sedan',
        priceSegment: 'economy',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2023',
        mileage: '10 000 км',
        priceMain: '10 000 ₸/сутки',
        basePrice: 10000,
        priceDiscount: '8 500 ₸/сутки при аренде от 3 дней',
        features: ['Мультимедийная система', 'Камера заднего вида', 'LED фары', 'Бесключевой доступ'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #fd746c, #ff9068)',
        city: 'karaganda'
    },
    hyundai_elantra_54419: {
        id: 'hyundai_elantra_54419',
        title: 'Hyundai Elantra',
        description: 'Экономичный и практичный седан для повседневных поездок.',
        type: 'sedan',
        priceSegment: 'economy',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        mileage: '30 000 км',
        priceMain: '9 000 ₸/сутки',
        basePrice: 9000,
        priceDiscount: '7 500 ₸/сутки при аренде от 3 дней',
        features: ['Кондиционер', 'Мультимедийная система', 'Электроусилитель руля'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #a8c0ff, #3f2b96)',
        city: 'karaganda'
    },

    // Внедорожники
    hyundai_santa_fe_40891: {
        id: 'hyundai_santa_fe_40891',
        title: 'Hyundai Santa Fe',
        description: 'Просторный внедорожник для семьи и путешествий по любым дорогам.',
        type: 'suv',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Внедорожник',
        year: '2022',
        mileage: '22 000 км',
        priceMain: '18 000 ₸/сутки',
        basePrice: 18000,
        priceDiscount: '15 000 ₸/сутки при аренде от 3 дней',
        features: ['Полный привод', 'Трехзонный климат-контроль', 'Панорамная крыша', 'Система парковки'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #ffd89b, #19547b)',
        city: 'astana'
    },
    hyundai_palisade_50339: {
        id: 'hyundai_palisade_50339',
        title: 'Hyundai Palisade',
        description: 'Просторный полноразмерный внедорожник премиум-класса.',
        type: 'suv',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Внедорожник',
        year: '2023',
        mileage: '18 000 км',
        priceMain: '20 000 ₸/сутки',
        basePrice: 20000,
        priceDiscount: '17 000 ₸/сутки при аренде от 3 дней',
        features: ['Полный привод', 'Память сидений', 'Вентиляция сидений', 'Хэд-ап дисплей'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #4da0ff, #d39d38)',
        city: 'almaty'
    },
    chery_tiggo_64982: {
        id: 'chery_tiggo_64982',
        title: 'Chery Tiggo 7 Pro',
        description: 'Современный кроссовер с богатой комплектацией и стильным дизайном.',
        type: 'suv',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Внедорожник',
        year: '2023',
        mileage: '12 000 км',
        priceMain: '14 000 ₸/сутки',
        basePrice: 14000,
        priceDiscount: '12 000 ₸/сутки при аренде от 3 дней',
        features: ['Панорамная крыша', 'Камера 360°', 'Бесключевой доступ', 'Светодиодные фары'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #ff7e5f, #feb47b)',
        city: 'astana'
    },
    jetour_t2_66170: {
        id: 'jetour_t2_66170',
        title: 'Jetour T2',
        description: 'Стильный внедорожник для активного образа жизни и путешествий.',
        type: 'suv',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Внедорожник',
        year: '2023',
        mileage: '8 000 км',
        priceMain: '13 000 ₸/сутки',
        basePrice: 13000,
        priceDiscount: '11 000 ₸/сутки при аренде от 3 дней',
        features: ['Полный привод', 'Мультимедийная система', 'Подогрев сидений', 'Круиз-контроль'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #74ebd5, #9face6)',
        city: 'karaganda'
    },
    lixiang_l9_59408: {
        id: 'lixiang_l9_59408',
        title: 'Lixiang L9 Ultra',
        description: 'Инновационный гибридный внедорожник премиум-класса с передовыми технологиями.',
        type: 'suv',
        priceSegment: 'premium',
        seats: '6 мест',
        transmission: 'Автомат',
        fuel: 'Гибрид',
        carType: 'Внедорожник',
        year: '2023',
        mileage: '5 000 км',
        priceMain: '28 000 ₸/сутки',
        basePrice: 28000,
        priceDiscount: '25 000 ₸/сутки при аренде от 3 дней',
        features: ['Гибридная установка', 'Автопилот', 'Премиум аудио', 'Массаж сидений', 'Панорамная крыша'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #8e2de2, #4a00e0)',
        city: 'almaty'
    },

    // Минивэны
    hyundai_custin_65678: {
        id: 'hyundai_custin_65678',
        title: 'Hyundai Custin',
        description: 'Вместительный минивэн для комфортных поездок большой компанией.',
        type: 'minivan',
        priceSegment: 'business',
        seats: '7 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Минивэн',
        year: '2023',
        mileage: '10 000 км',
        priceMain: '16 000 ₸/сутки',
        basePrice: 16000,
        priceDiscount: '14 000 ₸/сутки при аренде от 3 дней',
        features: ['Сдвижные двери', 'Трехзонный климат-контроль', 'Система парковки', 'Подогрев сидений'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #00c6ff, #0072ff)',
        city: 'astana'
    },
    kia_carnival_67829: {
        id: 'kia_carnival_67829',
        title: 'KIA Carnival',
        description: 'Просторный и комфортабельный минивэн премиум-класса.',
        type: 'minivan',
        priceSegment: 'business',
        seats: '8 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Минивэн',
        year: '2023',
        mileage: '12 000 км',
        priceMain: '18 000 ₸/сутки',
        basePrice: 18000,
        priceDiscount: '16 000 ₸/сутки при аренде от 3 дней',
        features: ['Электропривод дверей', 'Двухзонный климат-контроль', 'Система развлечений', 'Подогрев руля'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #f46b45, #eea849)',
        city: 'almaty'
    },

    // Дополнительные Toyota Camry
    toyota_camry_50336: {
        id: 'toyota_camry_50336',
        title: 'Toyota Camry 75',
        description: 'Обновленная версия популярного седана с улучшенной комфортностью.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        mileage: '18 000 км',
        priceMain: '13 500 ₸/сутки',
        basePrice: 13500,
        priceDiscount: '11 500 ₸/сутки при аренде от 3 дней',
        features: ['Обновленный дизайн', 'Улучшенная шумоизоляция', 'Мультимедийная система'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #ff6b6b, #ff8e8e)',
        city: 'astana'
    },
    toyota_camry_66223: {
        id: 'toyota_camry_66223',
        title: 'Toyota Camry',
        description: 'Классический седан с отличной репутацией надежности.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2022',
        mileage: '22 000 км',
        priceMain: '13 000 ₸/сутки',
        basePrice: 13000,
        priceDiscount: '11 000 ₸/сутки при аренде от 3 дней',
        features: ['Кондиционер', 'Круиз-контроль', 'Мультимедийная система'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #ff6b6b, #ff8e8e)',
        city: 'karaganda'
    },
    toyota_camry_55028: {
        id: 'toyota_camry_55028',
        title: 'Toyota Camry 70',
        description: 'Надежный седан для деловых поездок и повседневного использования.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2021',
        mileage: '35 000 км',
        priceMain: '12 000 ₸/сутки',
        basePrice: 12000,
        priceDiscount: '10 000 ₸/сутки при аренде от 3 дней',
        features: ['Кондиционер', 'Электростеклоподъемники', 'Мультимедийная система'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #ff6b6b, #ff8e8e)',
        city: 'almaty'
    },
    toyota_camry_40896: {
        id: 'toyota_camry_40896',
        title: 'Toyota Camry 70',
        description: 'Проверенный временем седан с оптимальным сочетанием цены и качества.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2021',
        mileage: '40 000 км',
        priceMain: '12 000 ₸/сутки',
        basePrice: 12000,
        priceDiscount: '10 000 ₸/сутки при аренде от 3 дней',
        features: ['Кондиционер', 'Круиз-контроль', 'Мультимедийная система'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #ff6b6b, #ff8e8e)',
        city: 'karaganda'
    },
    hyundai_sonata_66808: {
        id: 'hyundai_sonata_66808',
        title: 'Hyundai Sonata',
        description: 'Современный седан с привлекательным дизайном и хорошей комплектацией.',
        type: 'sedan',
        priceSegment: 'comfort',
        seats: '5 мест',
        transmission: 'Автомат',
        fuel: 'Бензин',
        carType: 'Седан',
        year: '2023',
        mileage: '15 000 км',
        priceMain: '12 500 ₸/сутки',
        basePrice: 12500,
        priceDiscount: '10 500 ₸/сутки при аренде от 3 дней',
        features: ['Климат-контроль', 'Круиз-контроль', 'Камера заднего вида', 'Светодиодные фары'],
        images: ['main.jpg', 'interior.jpg', 'exterior.jpg', 'dashboard.jpg'],
        color: 'linear-gradient(135deg, #667eea, #764ba2)',
        city: 'astana'
    }
};